apiVersion: v1
kind: Service
metadata:
  name: {{ include "gblog.fullname" . }}
  labels:
    app: {{ include "gblog.name" . }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort | default 8081 }}
      protocol: TCP
  selector:
    app: {{ include "gblog.name" . }}
