apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gblog.fullname" . }}-network-policy
  labels:
    app: {{ include "gblog.name" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "gblog.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              app: nginx-ingress
      ports:
        - protocol: TCP
          port: 8081
    - from:
        - podSelector:
            matchLabels:
              app: otel-collector
      ports:
        - protocol: TCP
          port: 8081
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: otel-collector
      ports:
        - protocol: TCP
          port: 4317
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: vault
      ports:
        - protocol: TCP
          port: 8200
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
