apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    service:
      pipelines:
        traces:
          receivers: ["otlp"]
          exporters: ["logging", "otlp"]
