{{- if .Values.rollout.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "gblog.fullname" . }}-rollout
  labels:
    app: {{ include "gblog.name" . }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gblog.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gblog.name" . }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8081
  strategy:
    canary:
      analysis:
        templates:
          - templateName: gblog-success-rate
        args:
          - name: service-name
            value: {{ include "gblog.fullname" . }}
      steps:
        - setWeight: 10
        - pause: { duration: 300s }
        - setWeight: 50
        - pause: { duration: 300s }
        - setWeight: 100
{{- end -}}
