backend:
  replicaCount: 1
  image:
    repository: shriganeshdockerhub/gblog-backend
    tag: "staging"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081

frontend:
  replicaCount: 1
  image:
    repository: shriganeshdockerhub/gblog-frontend
    tag: "staging"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

env:
  - name: NODE_ENV
    value: staging
  - name: LOG_LEVEL
    value: debug

otel:
  enabled: true
  endpoint: "http://otel-collector-staging:4317"

vault:
  enabled: false
