jenkins:
  systemMessage: "G-Blog X Jenkins configured via Configuration as Code (JCasC)"
  numExecutors: 2
  scmCheckoutRetryCount: 2
  mode: NORMAL

  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "admin"
          password: "${ADMIN_PASSWORD}"
  
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  sonarGlobalConfiguration:
    server:
      - name: "SonarQube"
        serverUrl: "http://localhost:9000"
        credentialsId: "sonar-token"
        installations:
          - name: "SonarScanner"

tool:
  maven:
    installations:
      - name: "maven-3.9"
        home: "/usr/share/maven"
  jdk:
    installations:
      - name: "jdk-21"
        home: "/usr/lib/jvm/java-21-openjdk-amd64"
  dockerTool:
    installations:
      - name: "docker"
        home: "/usr/bin/docker"

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "sonar-token"
              secret: "${SONAR_TOKEN}"
          - aws:
              scope: GLOBAL
              id: "aws-creds"
              accessKey: "${AWS_ACCESS_KEY_ID}"
              secretKey: "${AWS_SECRET_ACCESS_KEY}"
          - usernamePassword:
              scope: GLOBAL
              id: "docker-hub"
              username: "${DOCKER_HUB_USER}"
              password: "${DOCKER_HUB_TOKEN}"
          - usernamePassword:
              scope: GLOBAL
              id: "github-creds"
              username: "${GITHUB_USER}"
              password: "${GITHUB_TOKEN}"

jobs:
  - script: >
      pipelineJob('G-Blog-Pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/shriganeshchoudhari/blog-app.git')
                  credentials('github-creds')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
