apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gblog-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shriganeshchoudhari/blog-app.git
    targetRevision: HEAD
    path: helm/gblog
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
